### ISSUE TITLE
Problem with --prediction-rest-api on windows

### ISSUE THREAD

**Issue by msochor1** [matthew-sochor-zz/transfer#5]
email from Pat:

```
Ok.  Little farther...

PS C:\Users\pdl\Documents\transfer\MS1135A>> transfer --prediction-rest-api --project trail-cam-animal-v-empty
c:\program files\python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of iss
ubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).typ
e`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Project selected: trail-cam-animal-v-empty
2018-01-26 13:36:19.035538: I C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_
guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX
Loading model weights: C:\Users\pdl\.transfer\import\trail-cam-animal-v-empty\server_model_kfold_0.hdf5

To predict a local image, simply:

curl http://localhost:5000/predict -d "img_path=/path/to/your/img.png" -X POST

or

curl http://localhost:5000/predict -d "img_path=/path/to/your/img_dir" -X POST

Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\transfer.exe\__main__.py", line 9, in <module>
  File "c:\program files\python36\lib\site-packages\transfer\__main__.py", line 143, in main
    start_server(project, 'server_weights')
  File "c:\program files\python36\lib\site-packages\transfer\server.py", line 82, in start_server
    app.run(port = str(project['api_port']))
  File "c:\program files\python36\lib\site-packages\flask\app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "c:\program files\python36\lib\site-packages\werkzeug\serving.py", line 748, in run_simple
    raise TypeError('port must be an integer')
TypeError: port must be an integer
```

**Comment by msochor1** [comment]
My response:

```
Looks like you are trying the prediction rest api.  A few quick questions:

1. Have you tried the --predict yet? If yes, did it work? If no, please try that. Its a little more straightforward. 

2. Can you look in ~\.transfer\config.yaml and see what value is in a field called port? Or something like server_port? Is that number an integer? If no, make it sooner integer like 12345 or 8888 that is an open port you aren't using.

The rest api was thought of as a way to set up a computer to be ready to predict but not necessarily always predicting, like our web server for the first app. Regular predict was what i thought people would use more for standard batch predicting.

Matt
```
